### PR TITLE
Update parent version to 9.11 #64

### PR DESCRIPTION
**Pull request by ignatescustefan**
Updated dependencies and parent version from POM

### CODE REVIEW

**Comment by acotiuga** [comment]
There is also the readme file https://github.com/xwikisas/application-meeting/blob/master/README.md that needs to be updated with the new minimal supported version.

**Comment by acotiuga** [comment]
Another suggestion is to export the application structure from an instance of XWiki 9.11, apply `mvn xar:format` twice and commit the pages with the new format.

**Comment by oanalavinia** [comment]
There is also an object that needs to be deleted along with the dependency of Default Page Template Application https://github.com/xwikisas/application-meeting/blob/master/ui/src/main/resources/Meeting/WebHome.xml#L43

**Comment by acotiuga** [comment]
What have you done so far is good. You only need to be sure that all the pages from the application are exported. It looks that either you had some issues in exporting all the pages or you managed to skip some of them.

**Comment by mflorea** [comment]
Yes, it looks good except for the missing wiki pages.

**Comment by ignatescustefan** [comment]
I exported again the application and the only difference between the pages was the content of 'data' tag and 'contentUpdateDate' tag.

**Comment by mflorea** [comment]
Don't forget to close the issue.

**Pull request merged**
